# Generated by Django 4.1.7 on 2023-03-28 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksmainmodel',
            name='marks',
            field=models.ManyToManyField(default='', to='student.studentmarksmodel'),
        ),
        migrations.AlterField(
            model_name='studentmarksmainmodel',
            name='student',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='student.studentmainmodel'),
        ),
        migrations.AlterField(
            model_name='studentmarksmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmainmodel'),
        ),
    ]
