# Generated by Django 4.1.7 on 2023-03-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentmarksmainmodel_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmarksmainmodel',
            name='marks',
            field=models.ManyToManyField(default='', to='student.studentmarksmodel'),
        ),
    ]
